- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Install certbot and nginx plugin
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Create nginx config for Grafana
  ansible.builtin.template:
    src: grafana_proxy.conf.j2
    dest: /etc/nginx/sites-available/grafana
    owner: root
    group: root
    mode: '0644'

- name: Enable Grafana site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/grafana
    dest: /etc/nginx/sites-enabled/grafana
    state: link

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Obtain SSL cert via certbot
  ansible.builtin.command:
    cmd: "certbot --nginx --non-interactive --agree-tos --email {{ certbot_email }} -d {{ grafana_domain }}"
  args:
    creates: "/etc/letsencrypt/live/{{ grafana_domain }}"
