- name: Ensure nginx is installed
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure certbot is installed
  apt:
    name: certbot
    state: present
    update_cache: yes

- name: Ensure directory for Let's Encrypt challenges exists
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create nginx config for Grafana (HTTP -> HTTPS redirect + HTTPS handling)
  template:
    src: grafana_proxy.conf.j2
    dest: /etc/nginx/sites-available/{{ grafana_domain }}

- name: Enable nginx config
  file:
    src: /etc/nginx/sites-available/{{ grafana_domain }}
    dest: /etc/nginx/sites-enabled/{{ grafana_domain }}
    state: link
    force: yes

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Obtain Let's Encrypt cert for Grafana
  command: certbot certonly --webroot -w /var/www/html -d {{ grafana_domain }} --noninteractive --agree-tos --register-unsafely-without-email
  args:
    creates: "/etc/letsencrypt/live/{{ grafana_domain }}/fullchain.pem"

- name: Reload nginx again (after getting cert)
  systemd:
    name: nginx
    state: reloaded
